-- tabla usuario
create table usuario (
    id bigint generated by default as identity primary key,
    nombre varchar(120) not null,
    email varchar(160) not null unique,
    password_hash varchar(255) not null,
    telefono varchar(30),
    rol varchar(30) not null default 'VOLUNTARIO'
        check (rol in ('ADMIN', 'COORDINADOR', 'RESCATISTA', 'VOLUNTARIO', 'GESTOR_REFUGIO')),
    activo boolean not null default true,
    habilidades text,
    disponible boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

-- tabla zona
create table zona (
    id bigint generated by default as identity primary key,
    nombre varchar(120) not null,
    municipio varchar(120),
    departamento varchar(120),
    latitud numeric(9,6),
    longitud numeric(9,6),
    nivel_riesgo varchar(20) not null default 'MEDIO'
        check (nivel_riesgo in ('BAJO', 'MEDIO', 'ALTO', 'CRITICO')),
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);


-- listar todos los usuarios activos
create or replace function sp_listar_usuarios()
returns table (
    id bigint,
    nombre varchar,
    email varchar,
    telefono varchar,
    rol varchar,
    activo boolean,
    habilidades text,
    disponible boolean,
    created_at timestamptz
) as $$
begin
    return query
    select u.id, u.nombre, u.email, u.telefono, u.rol, u.activo, 
           u.habilidades, u.disponible, u.created_at
    from usuario u
    where u.activo = true
    order by u.created_at desc;
end;
$$ language plpgsql;

-- agregar nuevo usuario
create or replace procedure sp_agregar_usuario(
    p_nombre varchar,
    p_email varchar,
    p_password_hash varchar,
    p_telefono varchar default null,
    p_rol varchar default 'VOLUNTARIO',
    p_habilidades text default null,
    p_disponible boolean default false
) as $$
begin
    insert into usuario (nombre, email, password_hash, telefono, rol, habilidades, disponible)
    values (p_nombre, p_email, p_password_hash, p_telefono, p_rol, p_habilidades, p_disponible);
end;
$$ language plpgsql;

-- buscar usuario por id
create or replace function sp_buscar_usuario(p_id bigint)
returns table (
    id bigint,
    nombre varchar,
    email varchar,
    telefono varchar,
    rol varchar,
    activo boolean,
    habilidades text,
    disponible boolean,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select u.*
    from usuario u
    where u.id = p_id and u.activo = true;
end;
$$ language plpgsql;

-- actualizar usuario
create or replace procedure sp_actualizar_usuario(
    p_id bigint,
    p_nombre varchar,
    p_email varchar,
    p_telefono varchar,
    p_rol varchar,
    p_habilidades text,
    p_disponible boolean
) as $$
begin
    update usuario
    set nombre = p_nombre,
        email = p_email,
        telefono = p_telefono,
        rol = p_rol,
        habilidades = p_habilidades,
        disponible = p_disponible,
        updated_at = now()
    where id = p_id and activo = true;
end;
$$ language plpgsql;

-- eliminar usuario
create or replace procedure sp_eliminar_usuario(p_id bigint) as $$
begin
    update usuario
    set activo = false,
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;

-- listar todas las zonas activas
create or replace function sp_listar_zonas()
returns table (
    id bigint,
    nombre varchar,
    municipio varchar,
    departamento varchar,
    latitud numeric,
    longitud numeric,
    nivel_riesgo varchar,
    activo boolean,
    created_at timestamptz
) as $$
begin
    return query
    select z.id, z.nombre, z.municipio, z.departamento, z.latitud, z.longitud,
           z.nivel_riesgo, z.activo, z.created_at
    from zona z
    where z.activo = true
    order by z.nombre;
end;
$$ language plpgsql;

-- agregar nueva zona
create or replace procedure sp_agregar_zona(
    p_nombre varchar,
    p_municipio varchar default null,
    p_departamento varchar default null,
    p_latitud numeric default null,
    p_longitud numeric default null,
    p_nivel_riesgo varchar default 'MEDIO'
) as $$
begin
    insert into zona (nombre, municipio, departamento, latitud, longitud, nivel_riesgo)
    values (p_nombre, p_municipio, p_departamento, p_latitud, p_longitud, p_nivel_riesgo);
end;
$$ language plpgsql;

-- buscar zona por id
create or replace function sp_buscar_zona(p_id bigint)
returns table (
    id bigint,
    nombre varchar,
    municipio varchar,
    departamento varchar,
    latitud numeric,
    longitud numeric,
    nivel_riesgo varchar,
    activo boolean,
    created_at timestamptz,
    updated_at timestamptz
) as $$
begin
    return query
    select z.*
    from zona z
    where z.id = p_id and z.activo = true;
end;
$$ language plpgsql;

-- actualizar zona
create or replace procedure sp_actualizar_zona(
    p_id bigint,
    p_nombre varchar,
    p_municipio varchar,
    p_departamento varchar,
    p_latitud numeric,
    p_longitud numeric,
    p_nivel_riesgo varchar
) as $$
begin
    update zona
    set nombre = p_nombre,
        municipio = p_municipio,
        departamento = p_departamento,
        latitud = p_latitud,
        longitud = p_longitud,
        nivel_riesgo = p_nivel_riesgo,
        updated_at = now()
    where id = p_id and activo = true;
end;
$$ language plpgsql;

-- eliminar zona
create or replace procedure sp_eliminar_zona(p_id bigint) as $$
begin
    update zona
    set activo = false,
        updated_at = now()
    where id = p_id;
end;
$$ language plpgsql;
